config/routes.rb
HerokuDeployLab::Application.routes.draw do
  resources :computers

end

app/models/computer.rb
class Computer < ActiveRecord::Base
  attr_accessible :make, :model, :processor_speed
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/computers_controller.rb
class ComputersController < ApplicationController
  # GET /computers
  # GET /computers.json
  def index
    @computers = Computer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @computers }
    end
  end

  # GET /computers/1
  # GET /computers/1.json
  def show
    @computer = Computer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @computer }
    end
  end

  # GET /computers/new
  # GET /computers/new.json
  def new
    @computer = Computer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @computer }
    end
  end

  # GET /computers/1/edit
  def edit
    @computer = Computer.find(params[:id])
  end

  # POST /computers
  # POST /computers.json
  def create
    @computer = Computer.new(params[:computer])

    respond_to do |format|
      if @computer.save
        format.html { redirect_to @computer, notice: 'Computer was successfully created.' }
        format.json { render json: @computer, status: :created, location: @computer }
      else
        format.html { render action: "new" }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /computers/1
  # PUT /computers/1.json
  def update
    @computer = Computer.find(params[:id])

    respond_to do |format|
      if @computer.update_attributes(params[:computer])
        format.html { redirect_to @computer, notice: 'Computer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @computer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /computers/1
  # DELETE /computers/1.json
  def destroy
    @computer = Computer.find(params[:id])
    @computer.destroy

    respond_to do |format|
      format.html { redirect_to computers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/computers_helper.rb
module ComputersHelper
end

app/views/computers/_form.html.erb
<%= form_for(@computer) do |f| %>
  <% if @computer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@computer.errors.count, "error") %> prohibited this computer from being saved:</h2>

      <ul>
      <% @computer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :make %><br />
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :processor_speed %><br />
    <%= f.number_field :processor_speed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/computers/edit.html.erb
<h1>Editing computer</h1>

<%= render 'form' %>

<%= link_to 'Show', @computer %> |
<%= link_to 'Back', computers_path %>

app/views/computers/index.html.erb
<h1>Listing Computers</h1>

<table>
  <tr>
    <th>Make</th>
    <th>Model</th>
    <th>Processor speed</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @computers.each do |computer| %>
  <tr>
    <td><%= computer.make %></td>
    <td><%= computer.model %></td>
    <td><%= computer.processor_speed %></td>
    <td><%= link_to 'Show', computer %></td>
    <td><%= link_to 'Edit', edit_computer_path(computer) %></td>
    <td><%= link_to 'Destroy', computer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Computer', new_computer_path %>

app/views/computers/new.html.erb
<h1>New computer</h1>

<%= render 'form' %>

<%= link_to 'Back', computers_path %>

app/views/computers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Make:</b>
  <%= @computer.make %>
</p>

<p>
  <b>Model:</b>
  <%= @computer.model %>
</p>

<p>
  <b>Processor speed:</b>
  <%= @computer.processor_speed %>
</p>


<%= link_to 'Edit', edit_computer_path(@computer) %> |
<%= link_to 'Back', computers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HerokuDeployLab</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>